apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- .Values.airflow.prefix -}}airflow-env"
data:
  AIRFLOW_HOME: "/usr/local/airflow"
  {{- if .Values.airflow.fernet_key }}
  FERNET_KEY: "{{- .Values.airflow.fernet_key -}}"
  {{- end }}
  RABBITMQ_HOST: "{{- .Values.airflow.prefix -}}{{- .Values.db.rabbitmq.basename -}}"
  {{- if .Values.db.rabbitmq.user }}
  RABBITMQ_CREDS: "{{- .Values.db.rabbitmq.user -}}:{{- .Values.db.rabbitmq.password -}}"
  {{- end }}
  POSTGRES_HOST: "{{- .Values.airflow.prefix -}}{{- .Values.db.postgres.basename -}}"
  {{- if .Values.db.postgres.user }}
  POSTGRES_CREDS: "{{- .Values.db.postgres.user -}}:{{- .Values.db.postgres.password -}}"
  {{- end }}
  {{- if .Values.airflow.init_retry_loop }}
  TRY_LOOP: "{{ .Values.airflow.init_retry_loop -}}"
  {{- end }}
  FLOWER_URL_PREFIX: "{{ .Values.flower.url_prefix -}}"
  AIRFLOW_URL_PREFIX: "{{ .Values.airflow.url_prefix -}}"
  {{ if .Values.dags.git_sync_enabled }}
  GIT_SYNC_REPO: "{{ .Values.dags.git_repo }}"
  GIT_SYNC_BRANCH: "{{ .Values.dags.git_branch }}"
  GIT_SYNC_WAIT: "{{ .Values.dags.poll_interval_sec }}"
  GIT_SYNC_DEBUG: "{{ .Values.dags.git_sync_debug }}"
  {{ end }}
  LOAD_DAGS_EXAMPLES: "{{ .Values.dags.load_examples }}"
