apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{- .Values.airflow.prefix -}}web"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      restartPolicy: Always
      containers:
        - name: "{{- .Values.airflow.prefix -}}web"
          image: {{ .Values.airflow.image }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          envFrom:
            - configMapRef:
                name: "{{- .Values.airflow.prefix -}}airflow-env"
          ports:
            - name: "{{- .Values.airflow.prefix -}}web"
              containerPort: 8080
          {{- if .Values.airflow.airflow_cfg.enable }}
          volumeMounts:
            - mountPath: /usr/local/airflow-cm/
              name: "{{ .Values.airflow.prefix -}}airflow-cfg"
          command: ["bash", "/usr/local/airflow-cm/bootstrap.sh"]
          {{- end }}
          args: ["webserver"]
      {{- if .Values.airflow.airflow_cfg.enable }}
      volumes:
        - name: "{{ .Values.airflow.prefix -}}airflow-cfg"
          configMap:
            name: "{{ .Values.airflow.prefix -}}airflow.cfg"
      {{ end -}}
