apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.prefix -}}postgres
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - name: {{ .Values.airflow.prefix -}}postgres
      protocol: TCP
      port: 5432
      targetPort: {{ .Values.airflow.prefix -}}postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.prefix -}}rabbitmq
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: rabbitmq
  ports:
    - name: {{ .Values.airflow.prefix -}}node
      protocol: TCP
      port: 5672
      targetPort: {{ .Values.airflow.prefix -}}node
    - name: {{ .Values.airflow.prefix -}}management
      protocol: TCP
      port: 15672
      targetPort: {{ .Values.airflow.prefix -}}management
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.prefix -}}web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: {{ .Values.airflow.prefix -}}web
      protocol: TCP
      port: 8080
      name: {{ .Values.airflow.prefix -}}pweb
      targetPort: {{ .Values.airflow.prefix -}}web
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.prefix -}}flower
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: {{ .Values.airflow.prefix -}}flower
      protocol: TCP
      port: 5555
      name: {{ .Values.airflow.prefix -}}pflower
      targetPort: {{ .Values.airflow.prefix -}}flower
      nodePort: 32081
